package com.example.firstapplication.exceptionTest

fun main() {
    val a : Number = 1
    val b : Double = a as Double
}